### ISSUE TITLE
Split DiscUtils in multiple packages

### ISSUE THREAD

**Issue by qmfrederik** [quamotion/discutils#11]
@LordMike has done the rather impressive work of splitting DiscUtils in seperate packages.

This issues it to track whether we'd RI these changes into this repo, or attempt to handover the ownership of discutils to @LordMike.

Net, this issue serves as a continuation of the discussion on #9.

**Comment by qmfrederik** [comment]
@LordMike, looking at the delta in your repo, would you be open to an effort to attempt to squash some of the changes you made? Right now the history contains a lot of "Cleanup using Resharper" commits, I guess these could be squashed to make the history a bit more readable.

That way, we'd be able to take the changes in this repo as a PR.

**Comment by LordMike** [comment]
We could go another way entirely and register an OSS group with Github, get our own group and have DiscUtils as a project in that group .. Just a thought ;)

**Comment by qmfrederik** [comment]
That's fine with me, I think we can even move this repo to that project.

We could name it "DiscUtils", not sure if that's a good idea. Thoughts?

**Comment by LordMike** [comment]
I'm fine with DiscUtils (if we can hijack the Nuget package). Other names in that alley:

* Discs
* DiscTools
* DiscUtilities
* Filesystems
* DT
* DTools

**Comment by LordMike** [comment]
With #12 in order we can go ahead and create the DiscUtils group - and keep the name.

**Comment by qmfrederik** [comment]
OK - do you want me to transfer this repo to the DiscUtils project? It looks like that when I do that, we keep the entire history + redirects will be in place, so that should be cool.
