### ISSUE TITLE
Update the Discutils package on NuGet

### ISSUE THREAD

**Issue by qmfrederik** [quamotion/discutils#12]
The DiscUtils project, although still being used by many, is no longer being actively maintained in the original repositories:

- Original CodePlex project @ http://discutils.codeplex.com: Last change by festive_ken on Sep 25, 2014 (> 2,5 years ago)
- The DiscUtil package @ https://www.nuget.org/packages/Discutils/: Last change by @fearthecowboy on   Jun 15, 2013 (> 3,5 years ago)

We've been able to at least partially revamp some of the DiscUtils development in this repo, as well as the fork maintained by @LordMike. This includes making the code compatible with .NET Core and taking pull requests from the community.

This PR is to track us being able to have the DiscUtils NuGet packages updated.

Hence pinging @fearthecowboy and @coapp, who maintain the NuGet package, to see if there's a way we can collaborate and have an updated package on NuGet?

**Comment by fearthecowboy** [comment]
I can transfer the ownership of the nuget package to you if you'd like.

I don't have time to do much with that at this point. My use of it ended, and I haven't got back to it.

Give me your NuGet account (or whoever you want to own it) and I'll transfer it to you.


G

**Comment by qmfrederik** [comment]
@fearthecowboy The NuGet account I use is: quamotion .

Happy to maintain the package, thanks for creating the package & maintaining it until now!

**Comment by fearthecowboy** [comment]
Done! You should get a email notification to accept.

**Comment by qmfrederik** [comment]
@fearthecowboy Got the invitation, accepted. Thx!
