### ISSUE TITLE
Unit Test seem to be broken

### ISSUE THREAD

**Issue by zivillian** [quamotion/discutils#15]
In PR #8 you asked for unit tests. I tried to execute the current tests, bad failed badly.

Can you explain how to run them, or what would be your preferred way to add tests?

Regards,
Bianco

**Comment by qmfrederik** [comment]
@zivillian Sorry for the late reply :)

We've teamed up with @LordMike and moved all the code to a new repository, https://github.com/DiscUtils/DiscUtils; and your last PRs are in progress of being moved over as part of DiscUtils/DiscUtils#18.

Good news is that the unit tests are back up and running; so if you're still up to it, unit tests are still more than welcome :).

For new PRs, it would also be great if you could send them to DiscUtils/DiscUtils.

Thanks!
