### ISSUE TITLE
Split DiscUtils into separate projects?

### ISSUE THREAD

**Issue by LordMike** [quamotion/discutils#5]
Great work on preparing this humongous library for .NET Core :)

Would it be an idea to follow the .NET Core conventions and separate the different parts into separate projects (assemblies and Nuget Packages)?

Ideally, I could `Install-Package Quamotion.Discutils.Ntfs` on my project, to get just the NTFS part - it would then reference core libraries as needed to provide just that.

I could help on splitting out the projects.

**Comment by qmfrederik** [comment]
Hi Michael,

Thanks for your interest in discutil!

Sure, splitting DiscUtils in smaller packages sounds like a good idea. While I don’t have time to work on this myself right now, I’d be happy to accept any PR that makes this possible.

I think the DiscUtils codebase is already fairly modular, so creating separate projects shouldn’t be too hard.

Feel free to send us a PR, happy to discuss further,

Frederik.

**Comment by LordMike** [comment]
I went ahead and forked your project, although I couldn't use the fork on Github, as LFS was disabled (security reasons). I've got my code here:
https://github.com/LordMike/discutils

In it you'll note that all projects currently compile, and I've split it up per part. I also have a few meta-packages for f.ex. Filesystems alone.

**Comment by qmfrederik** [comment]
Hi @LordMike 

Sure, sounds good. I've noticed you're based off the same git repository as we are, so we could still merge the changes if you're interested.

Are you interested in merging back these changes or would like to maintain them as a seperate project?

Frederik.

**Comment by LordMike** [comment]
For now I'll maintain them separately. I have a number of improvements in mind which will be easier on my own.
